import os
import json
import re
from groq import Groq
from config import LLM_MODEL

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

SYSTEM_PROMPT = """You are an expert forensic linguist specializing in distinguishing human-written text from AI-generated text.

Analyze the provided text and assess whether it was written by a human or generated by an AI system.

Consider the following dimensions in your holistic assessment:
- Semantic coherence: Does meaning flow naturally or feel over-engineered?
- Tonal consistency: Is the voice authentic and variable, or smooth and uniform?
- Stylistic patterns: Are sentence structures varied in a human way, or rhythmically optimized?
- Contextual grounding: Does the writing reflect lived experience, opinion, and specificity?
- Hedging and certainty: Does it over-qualify or speak with unearned confidence?
- Lexical choices: Are words chosen expressively or selected for generic clarity?

You must respond ONLY with a valid JSON object in this exact format:
{
  "confidence": <float between 0.0 and 1.0>,
  "classification": "<one of: Likely Human, Uncertain, Likely AI>",
  "reasoning": "<brief 1–2 sentence explanation>"
}

Confidence score interpretation:
- 0.00–0.39 → Likely Human
- 0.40–0.60 → Uncertain
- 0.61–1.00 → Likely AI

Do not include any text outside the JSON object."""


def signal1_response(text: str) -> dict:
    """
    LLM-based AI text detection signal using Groq's llama-3.3-70b-versatile.

    Args:
        text: The input text to classify.

    Returns:
        A dict with keys:
            - confidence (float): Score from 0.0 (human) to 1.0 (AI).
            - classification (str): "Likely Human", "Uncertain", or "Likely AI".
            - reasoning (str): Brief explanation from the model.
            - raw_response (str): The raw model output for auditing.
    """
    if not text or not text.strip():
        return {
            "llm_confidence_score": 0.5,
            "classification": "Uncertain",
            "reasoning": "Empty or blank input provided.",
            "raw_response": "",
        }

    completion = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Analyze the following text:\n\n{text}"},
        ],
        temperature=0.0,
        max_tokens=256,
    )

    raw = completion.choices[0].message.content.strip()

    # Strip markdown code fences if present
    clean = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw, flags=re.DOTALL).strip()

    parsed = json.loads(clean)

    confidence = float(parsed["confidence"])
    confidence = max(0.0, min(1.0, confidence))

    # Normalize classification against threshold table
    if confidence <= 0.39:
        classification = "Likely Human"
    elif confidence <= 0.60:
        classification = "Uncertain"
    else:
        classification = "Likely AI"

    return {
        "llm_confidence_score": round(confidence, 2),
        "classification": classification,
        "reasoning": parsed.get("reasoning", ""),
        "raw_response": raw,
    }

if __name__ == "__main__":
    print("Signal 1 Testing")
    # Empty String
    test_string0 = ""
    signal1_test0 = signal1_response(test_string0)
    print(signal1_test0["classification"], signal1_test0["llm_confidence_score"])

    # Human Response
    test_string = "The sun dipped below the horizon, painting the sky in hues of amber and rose. I sat on the porch, coffee in hand, watching the neighborhood slowly go quiet."
    signal1_test1 = signal1_response(test_string)
    print(signal1_test1["classification"], signal1_test1["llm_confidence_score"])
    
    # AI response
    test_string2 = """
    Discover the future of everyday convenience with our revolutionary smart-home device. 
    Seamlessly designed to integrate into your busy lifestyle, this product harnesses advanced automation to save you time and energy. 
    Whether you are managing your daily schedule or enjoying a quiet evening, our innovation ensures a truly elevated experience.
    """
    signal1_test2 = signal1_response(test_string2)
    print(signal1_test2["classification"], signal1_test2["llm_confidence_score"])

